// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	events "github.com/runatlantis/atlantis/server/events"
)

func AnyEventsPullCommand() events.PullCommand {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(events.PullCommand))(nil)).Elem()))
	var nullValue events.PullCommand
	return nullValue
}

func EqEventsPullCommand(value events.PullCommand) events.PullCommand {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue events.PullCommand
	return nullValue
}

func NotEqEventsPullCommand(value events.PullCommand) events.PullCommand {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue events.PullCommand
	return nullValue
}

func EventsPullCommandThat(matcher pegomock.ArgumentMatcher) events.PullCommand {
	pegomock.RegisterMatcher(matcher)
	var nullValue events.PullCommand
	return nullValue
}
